baseURL = 'https://jinjja.pages.dev'
languageCode = 'en-us'
title = 'Jinjja 진짜'
theme = 'diary'
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
subtitle = 'Find the best products for your cash'
description = 'Jinjja is a place to find the best products for your cash, we only list one choice - our aim is to reduce decision fatigue for the end user.'

[author]
  name = 'Sakshat Shinde'

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "sakshatshinde"


