baseURL = 'https://jinjja.pages.dev'
defaultContentLang = 'en'
title = 'Jinjja 진짜'
theme = 'diary'
enableRobotsTXT = true
googleAnalytics = 'G-2JV305BNZH'
defaultContentLanguage = 'en'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# [sitemap]
#   changefreq = 'daily'
#   filename = 'sitemap.xml'
#   priority = 0.5

[params]
subtitle = 'Find the best products for your cash'
description = 'Jinjja is a place to find the best products for your cash, we only list one choice - our aim is to reduce decision fatigue for the end user.'

[menu]
[[menu.main]]
  identifier = 'subscribe'
  name = 'Subscribe'
  url = '/subscribe/'

[server]
[[server.headers]]
  for = '/sitemap.xml'
  [server.headers.values]
    Content-Type = 'application/xml'

[[menu.main]]
  identifier = 'about'
  name = 'About Jinjja'
  url = '/about/'

[[menu.main]]
  identifier = 'electronics'
  name = 'Electronics'
  url = '/electronics/'

[[menu.main]]
  identifier = 'beauty'
  name = 'Beauty'
  url = '/beauty/'

[[menu.main]]
  identifier = 'promo'
  name = 'Promotions'
  url = '/promo/'

[author]
  name = 'Sakshat Shinde'

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "sakshatshinde"


